<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguagesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('languages')->insert(['language' => 'af', 'name' => 'Afrikaans']);
        DB::table('languages')->insert(['language' => 'am', 'name' => 'አማርኛ']);
        DB::table('languages')->insert(['language' => 'arg', 'name' => 'Aragonés']);
        DB::table('languages')->insert(['language' => 'ar', 'name' => 'العربية']);
        DB::table('languages')->insert(['language' => 'ary', 'name' => 'العربية المغربية']);
        DB::table('languages')->insert(['language' => 'as', 'name' => 'অসমীয়া']);
        DB::table('languages')->insert(['language' => 'azb', 'name' => 'گؤنئی آذربایجان']);
        DB::table('languages')->insert(['language' => 'az', 'name' => 'Azərbaycan dili']);
        DB::table('languages')->insert(['language' => 'bel', 'name' => 'Беларуская мова']);
        DB::table('languages')->insert(['language' => 'bg_BG', 'name' => 'Български']);
        DB::table('languages')->insert(['language' => 'bn_BD', 'name' => 'বাংলা']);
        DB::table('languages')->insert(['language' => 'bo', 'name' => 'བོད་ཡིག']);
        DB::table('languages')->insert(['language' => 'bs_BA', 'name' => 'Bosanski']);
        DB::table('languages')->insert(['language' => 'ca', 'name' => 'Català']);
        DB::table('languages')->insert(['language' => 'ceb', 'name' => 'Cebuano']);
        DB::table('languages')->insert(['language' => 'cs_CZ', 'name' => 'Čeština']);
        DB::table('languages')->insert(['language' => 'cy', 'name' => 'Cymraeg']);
        DB::table('languages')->insert(['language' => 'da_DK', 'name' => 'Dansk']);
        DB::table('languages')->insert(['language' => 'de_CH_informal', 'name' => 'Deutsch (Schweiz, Du)']);
        DB::table('languages')->insert(['language' => 'de_DE_formal', 'name' => 'Deutsch (Sie)']);
        DB::table('languages')->insert(['language' => 'de_AT', 'name' => 'Deutsch (Österreich)']);
        DB::table('languages')->insert(['language' => 'de_CH', 'name' => 'Deutsch (Schweiz)']);
        DB::table('languages')->insert(['language' => 'de_DE', 'name' => 'Deutsch']);
        DB::table('languages')->insert(['language' => 'dsb', 'name' => 'Dolnoserbšćina']);
        DB::table('languages')->insert(['language' => 'dzo', 'name' => 'རྫོང་ཁ']);
        DB::table('languages')->insert(['language' => 'el', 'name' => 'Ελληνικά']);
        DB::table('languages')->insert(['language' => 'en_CA', 'name' => 'English (Canada)']);
        DB::table('languages')->insert(['language' => 'en_ZA', 'name' => 'English (South Africa)']);
        DB::table('languages')->insert(['language' => 'en_NZ', 'name' => 'English (New Zealand)']);
        DB::table('languages')->insert(['language' => 'en_GB', 'name' => 'English (UK)']);
        DB::table('languages')->insert(['language' => 'en_AU', 'name' => 'English (Australia)']);
        DB::table('languages')->insert(['language' => 'eo', 'name' => 'Esperanto']);
        DB::table('languages')->insert(['language' => 'es_CR', 'name' => 'Español de Costa Rica']);
        DB::table('languages')->insert(['language' => 'es_MX', 'name' => 'Español de México']);
        DB::table('languages')->insert(['language' => 'es_VE', 'name' => 'Español de Venezuela']);
        DB::table('languages')->insert(['language' => 'es_CO', 'name' => 'Español de Colombia']);
        DB::table('languages')->insert(['language' => 'es_EC', 'name' => 'Español de Ecuador']);
        DB::table('languages')->insert(['language' => 'es_DO', 'name' => 'Español de República Dominicana']);
        DB::table('languages')->insert(['language' => 'es_PE', 'name' => 'Español de Perú']);
        DB::table('languages')->insert(['language' => 'es_UY', 'name' => 'Español de Uruguay']);
        DB::table('languages')->insert(['language' => 'es_CL', 'name' => 'Español de Chile']);
        DB::table('languages')->insert(['language' => 'es_PR', 'name' => 'Español de Puerto Rico']);
        DB::table('languages')->insert(['language' => 'es_AR', 'name' => 'Español de Argentina']);
        DB::table('languages')->insert(['language' => 'es_GT', 'name' => 'Español de Guatemala']);
        DB::table('languages')->insert(['language' => 'es_ES', 'name' => 'Español']);
        DB::table('languages')->insert(['language' => 'et', 'name' => 'Eesti']);
        DB::table('languages')->insert(['language' => 'eu', 'name' => 'Euskara']);
        DB::table('languages')->insert(['language' => 'fa_AF', 'name' => '(فارسی (افغانستان']);
        DB::table('languages')->insert(['language' => 'fa_IR', 'name' => 'فارسی']);
        DB::table('languages')->insert(['language' => 'fi', 'name' => 'Suomi']);
        DB::table('languages')->insert(['language' => 'fr_FR', 'name' => 'Français']);
        DB::table('languages')->insert(['language' => 'fr_CA', 'name' => 'Français du Canada']);
        DB::table('languages')->insert(['language' => 'fr_BE', 'name' => 'Français de Belgique']);
        DB::table('languages')->insert(['language' => 'fur', 'name' => 'Friulian']);
        DB::table('languages')->insert(['language' => 'fy', 'name' => 'Frysk']);
        DB::table('languages')->insert(['language' => 'gd', 'name' => 'Gàidhlig']);
        DB::table('languages')->insert(['language' => 'gl_ES', 'name' => 'Galego']);
        DB::table('languages')->insert(['language' => 'gu', 'name' => 'ગુજરાતી']);
        DB::table('languages')->insert(['language' => 'haz', 'name' => 'هزاره گی']);
        DB::table('languages')->insert(['language' => 'he_IL', 'name' => 'עִבְרִית']);
        DB::table('languages')->insert(['language' => 'hi_IN', 'name' => 'हिन्दी']);
        DB::table('languages')->insert(['language' => 'hr', 'name' => 'Hrvatski']);
        DB::table('languages')->insert(['language' => 'hsb', 'name' => 'Hornjoserbšćina']);
        DB::table('languages')->insert(['language' => 'hu_HU', 'name' => 'Magyar']);
        DB::table('languages')->insert(['language' => 'hy', 'name' => 'Հայերեն']);
        DB::table('languages')->insert(['language' => 'id_ID', 'name' => 'Bahasa Indonesia']);
        DB::table('languages')->insert(['language' => 'is_IS', 'name' => 'Íslenska']);
        DB::table('languages')->insert(['language' => 'it_IT', 'name' => 'Italiano']);
        DB::table('languages')->insert(['language' => 'ja', 'name' => '日本語']);
        DB::table('languages')->insert(['language' => 'jv_ID', 'name' => 'Basa Jawa']);
        DB::table('languages')->insert(['language' => 'ka_GE', 'name' => 'ქართული']);
        DB::table('languages')->insert(['language' => 'kab', 'name' => 'Taqbaylit']);
        DB::table('languages')->insert(['language' => 'kk', 'name' => 'Қазақ тілі']);
        DB::table('languages')->insert(['language' => 'km', 'name' => 'ភាសាខ្មែរ']);
        DB::table('languages')->insert(['language' => 'kn', 'name' => 'ಕನ್ನಡ']);
        DB::table('languages')->insert(['language' => 'ko_KR', 'name' => '한국어']);
        DB::table('languages')->insert(['language' => 'ckb', 'name' => 'كوردی‎']);
        DB::table('languages')->insert(['language' => 'kir', 'name' => 'Кыргызча']);
        DB::table('languages')->insert(['language' => 'lo', 'name' => 'ພາສາລາວ']);
        DB::table('languages')->insert(['language' => 'lt_LT', 'name' => 'Lietuvių kalba']);
        DB::table('languages')->insert(['language' => 'lv', 'name' => 'Latviešu valoda']);
        DB::table('languages')->insert(['language' => 'mk_MK', 'name' => 'Македонски јазик']);
        DB::table('languages')->insert(['language' => 'ml_IN', 'name' => 'മലയാളം']);
        DB::table('languages')->insert(['language' => 'mn', 'name' => 'Монгол']);
        DB::table('languages')->insert(['language' => 'mr', 'name' => 'मराठी']);
        DB::table('languages')->insert(['language' => 'ms_MY', 'name' => 'Bahasa Melayu']);
        DB::table('languages')->insert(['language' => 'my_MM', 'name' => 'ဗမာစာ']);
        DB::table('languages')->insert(['language' => 'nb_NO', 'name' => 'Norsk bokmål']);
        DB::table('languages')->insert(['language' => 'ne_NP', 'name' => 'नेपाली']);
        DB::table('languages')->insert(['language' => 'nl_NL', 'name' => 'Nederlands']);
        DB::table('languages')->insert(['language' => 'nl_NL_formal', 'name' => 'Nederlands (Formeel)']);
        DB::table('languages')->insert(['language' => 'nl_BE', 'name' => 'Nederlands (België)']);
        DB::table('languages')->insert(['language' => 'nn_NO', 'name' => 'Norsk nynorsk']);
        DB::table('languages')->insert(['language' => 'oci', 'name' => 'Occitan']);
        DB::table('languages')->insert(['language' => 'pa_IN', 'name' => 'ਪੰਜਾਬੀ']);
        DB::table('languages')->insert(['language' => 'pl_PL', 'name' => 'Polski']);
        DB::table('languages')->insert(['language' => 'ps', 'name' => 'پښتو']);
        DB::table('languages')->insert(['language' => 'pt_BR', 'name' => 'Português do Brasil']);
        DB::table('languages')->insert(['language' => 'pt_AO', 'name' => 'Português de Angola']);
        DB::table('languages')->insert(['language' => 'pt_PT_ao90', 'name' => 'Português (AO90)']);
        DB::table('languages')->insert(['language' => 'pt_PT', 'name' => 'Português']);
        DB::table('languages')->insert(['language' => 'rhg', 'name' => 'Ruáinga']);
        DB::table('languages')->insert(['language' => 'ro_RO', 'name' => 'Română']);
        DB::table('languages')->insert(['language' => 'ru_RU', 'name' => 'Русский']);
        DB::table('languages')->insert(['language' => 'sah', 'name' => 'Сахалыы']);
        DB::table('languages')->insert(['language' => 'snd', 'name' => 'سنڌي']);
        DB::table('languages')->insert(['language' => 'si_LK', 'name' => 'සිංහල']);
        DB::table('languages')->insert(['language' => 'sk_SK', 'name' => 'Slovenčina']);
        DB::table('languages')->insert(['language' => 'skr', 'name' => 'سرائیکی']);
        DB::table('languages')->insert(['language' => 'sl_SI', 'name' => 'Slovenščina']);
        DB::table('languages')->insert(['language' => 'sq', 'name' => 'Shqip']);
        DB::table('languages')->insert(['language' => 'sr_RS', 'name' => 'Српски језик']);
        DB::table('languages')->insert(['language' => 'sv_SE', 'name' => 'Svenska']);
        DB::table('languages')->insert(['language' => 'sw', 'name' => 'Kiswahili']);
        DB::table('languages')->insert(['language' => 'szl', 'name' => 'Ślōnskŏ gŏdka']);
        DB::table('languages')->insert(['language' => 'ta_IN', 'name' => 'தமிழ்']);
        DB::table('languages')->insert(['language' => 'ta_LK', 'name' => 'தமிழ்']);
        DB::table('languages')->insert(['language' => 'te', 'name' => 'తెలుగు']);
        DB::table('languages')->insert(['language' => 'th', 'name' => 'ไทย']);
        DB::table('languages')->insert(['language' => 'tl', 'name' => 'Tagalog']);
        DB::table('languages')->insert(['language' => 'tr_TR', 'name' => 'Türkçe']);
        DB::table('languages')->insert(['language' => 'tt_RU', 'name' => 'Татар теле']);
        DB::table('languages')->insert(['language' => 'tah', 'name' => 'Reo Tahiti']);
        DB::table('languages')->insert(['language' => 'ug_CN', 'name' => 'ئۇيغۇرچە']);
        DB::table('languages')->insert(['language' => 'uk', 'name' => 'Українська']);
        DB::table('languages')->insert(['language' => 'ur', 'name' => 'اردو']);
        DB::table('languages')->insert(['language' => 'uz_UZ', 'name' => 'O‘zbekcha']);
        DB::table('languages')->insert(['language' => 'vi', 'name' => 'Tiếng Việt']);
        DB::table('languages')->insert(['language' => 'zh_CN', 'name' => '简体中文']);
        DB::table('languages')->insert(['language' => 'zh_HK', 'name' => '香港中文']);
        DB::table('languages')->insert(['language' => 'zh_TW', 'name' => '繁體中文']);
    }
}
